"""SQLite storage for the fleet.

Two deliberate choices:

1. WAL journal mode. The dashboard reads constantly while heartbeats write
   constantly. In SQLite's default rollback journal a writer blocks readers;
   in WAL they run concurrently. Without this the dashboard visibly stutters
   once you have a handful of nodes.

2. One shared connection guarded by a lock, rather than a pool. Every write
   here is a single small INSERT/UPDATE measured in microseconds, and the
   lock is held only for that. This is the simplest thing that is correct.
   It would stop being adequate if we ever did long transactions or bulk
   analytical reads on the request log -- at that point, move to a
   connection-per-thread via threading.local. Not before.
"""

import sqlite3
import threading
import time
from pathlib import Path
from typing import Any, Iterable

SCHEMA = """
-- One row per machine that has ever joined. Rows are never deleted, so a
-- friend who left last month still shows in history with his last_seen.
CREATE TABLE IF NOT EXISTS nodes (
    id              TEXT PRIMARY KEY,   -- generated by the agent, persisted on
                                        -- the node so reinstalls keep identity
    name            TEXT NOT NULL,      -- hostname, for display
    ip              TEXT NOT NULL,      -- tailscale IP
    port            INTEGER NOT NULL,   -- where its inference server listens
    backend         TEXT NOT NULL,      -- 'ollama' | 'llamacpp'
    os              TEXT,
    arch            TEXT,
    gpu             TEXT,               -- human string, e.g. 'NVIDIA RTX 4070'
    vram_total_mb   INTEGER,
    ram_total_mb    INTEGER,
    agent_version   TEXT,
    first_seen      REAL NOT NULL,
    last_seen       REAL NOT NULL,
    -- Lets you park a flaky node without uninstalling anything on your
    -- friend's machine. Router skips disabled nodes; dashboard still shows it.
    enabled         INTEGER NOT NULL DEFAULT 1
);

-- Which models each node can serve. Separate table because it is a list, and
-- because the router queries it: "who has hermes3?" is the core lookup.
CREATE TABLE IF NOT EXISTS node_models (
    node_id  TEXT NOT NULL,
    model    TEXT NOT NULL,
    PRIMARY KEY (node_id, model)
);
CREATE INDEX IF NOT EXISTS idx_node_models_model ON node_models(model);

-- Time series, one row per heartbeat. This is what the VRAM/uptime graphs
-- read. Pruned by retention policy since it grows at ~17k rows/node/day.
CREATE TABLE IF NOT EXISTS heartbeats (
    node_id       TEXT NOT NULL,
    ts            REAL NOT NULL,
    vram_used_mb  INTEGER,
    ram_used_mb   INTEGER,
    cpu_pct       REAL
);
CREATE INDEX IF NOT EXISTS idx_heartbeats_node_ts ON heartbeats(node_id, ts);

-- One row per proxied request, written by the router. This is the ONLY
-- source of performance truth: the agent never reports latency or tok/sec,
-- because the proxy is in the data path and can measure it directly.
CREATE TABLE IF NOT EXISTS requests (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    ts                REAL NOT NULL,
    node_id           TEXT,             -- NULL if we never found a backend
    model             TEXT,
    stream            INTEGER NOT NULL DEFAULT 0,
    ttft_ms           REAL,             -- time to first token; NULL if failed
    total_ms          REAL,
    completion_tokens INTEGER,
    status            TEXT NOT NULL,    -- 'ok' | 'error' | 'no_backend'
    error             TEXT
);
CREATE INDEX IF NOT EXISTS idx_requests_node_ts ON requests(node_id, ts);
CREATE INDEX IF NOT EXISTS idx_requests_ts ON requests(ts);
"""


class Database:
    def __init__(self, path: Path):
        path.parent.mkdir(parents=True, exist_ok=True)
        # check_same_thread=False because FastAPI runs sync handler code in a
        # threadpool and we may touch this connection from any of those
        # threads. Safe only because every access goes through self._lock.
        self._conn = sqlite3.connect(str(path), check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        self._lock = threading.RLock()
        with self._lock:
            self._conn.execute("PRAGMA journal_mode=WAL")
            # NORMAL trades a tiny durability window on power loss for far
            # fewer fsyncs. We are storing telemetry, not money.
            self._conn.execute("PRAGMA synchronous=NORMAL")
            self._conn.executescript(SCHEMA)
            self._conn.commit()

    def query(self, sql: str, params: Iterable[Any] = ()) -> list[sqlite3.Row]:
        with self._lock:
            return self._conn.execute(sql, tuple(params)).fetchall()

    def query_one(self, sql: str, params: Iterable[Any] = ()) -> sqlite3.Row | None:
        rows = self.query(sql, params)
        return rows[0] if rows else None

    def execute(self, sql: str, params: Iterable[Any] = ()) -> sqlite3.Cursor:
        with self._lock:
            cur = self._conn.execute(sql, tuple(params))
            self._conn.commit()
            return cur

    def executemany(self, sql: str, rows: Iterable[Iterable[Any]]) -> None:
        with self._lock:
            self._conn.executemany(sql, [tuple(r) for r in rows])
            self._conn.commit()

    def prune(self, retention_days: int) -> int:
        """Drop heartbeat history older than the retention window."""
        cutoff = time.time() - retention_days * 86400
        cur = self.execute("DELETE FROM heartbeats WHERE ts < ?", (cutoff,))
        return cur.rowcount

    def close(self) -> None:
        with self._lock:
            self._conn.close()
